language: node_js
node_js:
  - "8"

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run build

after_success:
  - npm run firebase

notifications:
  email:
    recipients:
      - artem.verbat@gmail.com
      - vagapoff@mobiagency.ru
    on_failure: always
    on_success: always
