language: node_js
node_js:
  - "7"

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    recipients:
      - artem.verbat@gmail.com
    on_failure: always
    on_success: always
